/**
 * Framework API Types
 * Re-exports API types from @hai3/api
 *
 * NOTE: AccountsApiService has been moved to CLI templates.
 * It is now generated by `hai3 scaffold layout` and should be
 * imported from user code (e.g., @/layout/api or @/api).
 */

// This file is intentionally empty but kept for future framework-level API types
