#!/usr/bin/env node

import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

// Generate MFE manifests registry
// Generates src/app/mfe/generated-mfe-manifests.ts from all mfe.json files
// found in src/mfe_packages/*/mfe.json

const MFE_PACKAGES_DIR = join(process.cwd(), 'src/mfe_packages');
const OUTPUT_FILE = join(process.cwd(), 'src/app/mfe/generated-mfe-manifests.ts');

function typePreamble(): string {
  return `import type { Extension, JSONSchema, MfeEntry } from '@cyberfabric/react';

export interface MfeManifestConfig {
  manifest: JSONSchema;
  entries: MfeEntry[];
  extensions: Extension[];
  // @cpt-FEATURE:cpt-frontx-dod-screenset-registry-mfe-schema-registration:p1
  /** MFE-carried schemas (custom actions, properties). Registered before entries and extensions. */
  schemas?: JSONSchema[];
}`;
}

function generateManifestRegistry(): void {
  try {
    // Packages to exclude (shared libraries, hidden dirs, etc.)
    const EXCLUDED_PACKAGES = new Set(['.git', '.DS_Store']);

    // Find all MFE packages
    const mfePackages = readdirSync(MFE_PACKAGES_DIR).filter((dir) => {
      // Skip excluded packages and hidden directories
      if (EXCLUDED_PACKAGES.has(dir) || dir.startsWith('.')) {
        return false;
      }

      const mfeJsonPath = join(MFE_PACKAGES_DIR, dir, 'mfe.json');
      try {
        readFileSync(mfeJsonPath);
        return true;
      } catch {
        return false;
      }
    });

    console.log(`📦 Found ${mfePackages.length} MFE package(s):`);
    mfePackages.forEach((pkg) => {
      console.log(`  - ${pkg}`);
    });

    // Generate import statements
    const imports = mfePackages
      .map((pkg, idx) => {
        return `import mfe${idx} from '@/mfe_packages/${pkg}/mfe.json';`;
      })
      .join('\n');

    // Generate registry
    const registry = `export const MFE_MANIFESTS: MfeManifestConfig[] = [
${mfePackages
  .map((_, idx) => `  mfe${idx},`)
  .join('\n')}
];`;

    // Generate file content
    const content = `// AUTO-GENERATED FILE
// Generated by: scripts/generate-mfe-manifests.ts
// Do not edit manually!
// Regenerate: npm run generate:mfe-manifests

${imports}

${typePreamble()}

${registry}

// Get all MFE manifests
// Allows Vite to statically analyze imports without warnings
export function getMfeManifests() {
  return MFE_MANIFESTS;
}
`;

    writeFileSync(OUTPUT_FILE, content);
    console.log(`\n✅ Generated ${OUTPUT_FILE}`);
  } catch (error) {
    console.error('❌ Error generating MFE manifests:', error);
    process.exit(1);
  }
}

generateManifestRegistry();
