// @cpt-flow:cpt-frontx-flow-request-lifecycle-query-client-lifecycle:p2

/**
 * MFE Bootstrap
 *
 * Registers MFE domains, extensions, and handlers with the FrontX app.
 * This file is imported in main.tsx to wire MFE capabilities into the host app.
 *
 * MFE manifests are auto-generated by `npm run generate:mfe-manifests`
 * into ./generated-mfe-manifests. Run that script after adding or removing
 * MFE packages from src/mfe_packages/.
 */

import type { RefObject } from 'react';
import type { HAI3App, Extension, ScreenExtension } from '@cyberfabric/react';
import { bootstrapMfeDomains } from '@cyberfabric/react';
import { MFE_MANIFESTS, type MfeManifestConfig } from './generated-mfe-manifests';

// @cpt-begin:cpt-frontx-flow-request-lifecycle-query-client-lifecycle:p2:inst-is-screen-extension
function isScreenExtension(extension: Extension): extension is ScreenExtension {
  const candidate = extension as { presentation?: { route?: string } };
  return typeof candidate.presentation?.route === 'string';
}
// @cpt-end:cpt-frontx-flow-request-lifecycle-query-client-lifecycle:p2:inst-is-screen-extension

/**
 * Bootstrap MFE system for the host application.
 * Registers domains, extensions, and shared properties.
 * Mount/unmount lifecycle is delegated to ExtensionDomainSlot in MfeScreenContainer.
 *
 * @param app - FrontX application instance
 * @param screenContainerRef - React ref for the screen domain container element
 * @returns Array of registered screen extensions, for URL routing in MfeScreenContainer
 */
// @cpt-begin:cpt-frontx-flow-request-lifecycle-query-client-lifecycle:p2:inst-bootstrap-mfe
export async function bootstrapMFE(
  app: HAI3App,
  screenContainerRef: RefObject<HTMLDivElement | null>,
): Promise<ScreenExtension[]> {
  const screensetsRegistry = await bootstrapMfeDomains(app, screenContainerRef);

  if (MFE_MANIFESTS.length === 0) {
    console.warn('[MFE Bootstrap] No MFE manifests found. Run `npm run generate:mfe-manifests` to generate them.');
    return [];
  }

  const manifests = MFE_MANIFESTS as MfeManifestConfig[];
  const screenExtensions: ScreenExtension[] = [];

  for (const config of manifests) {
    // @cpt-begin:cpt-frontx-dod-screenset-registry-mfe-schema-registration:p1:inst-1
    // Register MFE-carried schemas (custom actions, properties) before entries so GTS
    // can validate entry references to these schemas at registration time.
    if (config.schemas) {
      for (const schema of config.schemas) {
        screensetsRegistry.typeSystem.registerSchema(schema);
      }
    }
    // @cpt-end:cpt-frontx-dod-screenset-registry-mfe-schema-registration:p1:inst-1

    // Register and validate manifest instance against GTS schema
    screensetsRegistry.typeSystem.register(config.manifest);
    const manifestValidation = screensetsRegistry.typeSystem.validateInstance(config.manifest.id);
    if (!manifestValidation.valid) {
      console.error(
        `[MFE Bootstrap] Manifest '${config.manifest.id}' failed GTS validation:`,
        JSON.stringify(manifestValidation.errors, null, 2)
      );
    }

    for (const entry of config.entries) {
      screensetsRegistry.typeSystem.register({ ...entry, manifest: config.manifest });
    }

    for (const extension of config.extensions) {
      await screensetsRegistry.registerExtension(extension);
    }

    screenExtensions.push(...config.extensions.filter(isScreenExtension));
  }

  return screenExtensions;
}
// @cpt-end:cpt-frontx-flow-request-lifecycle-query-client-lifecycle:p2:inst-bootstrap-mfe
